name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # <== permite "Run workflow"

env:
  TF_VERSION: 1.7.5
  AWS_REGION: eu-west-1

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./proyectotf

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: ./proyectotf

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./proyectotf

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./proyectotf

      - name: Upload tfplan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./proyectotf/tfplan

      - name: Show tfplan
        run: terraform show -no-color tfplan > plan.txt
        working-directory: ./proyectotf

      - name: Upload plan.txt artifact
        uses: actions/upload-artifact@v4
        with:
          name: plan.txt
          path: ./proyectotf/plan.txt

      - name: Comment PR with Terraform Plan
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Terraform Plan 📖
            ```
            ${{ steps.show_plan.outputs.plan }}
            ```

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        working-directory: ./proyectotf
